name: Customs check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Fetch target branch
        run: git fetch --depth=1 origin ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }}

      - name: Build customs
        run: go build -o customs cmd/customs/main.go

      - name: Customs inspection
        run: git diff origin/${{ github.event.pull_request.base.ref }}...HEAD | customs inspect
