name: publish-image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/manifest:latest -t ghcr.io/${{ github.repository }}/manifest:${{ github.ref_name }} .
          docker push ghcr.io/${{ github.repository }}/manifest:latest
          docker push ghcr.io/${{ github.repository }}/manifest:${{ github.ref_name }} 